### ISSUE TITLE
build issues on windows 11 home

### ISSUE THREAD

**Issue by havbon** [bramtechs/basalt#32]
https://pastebin.com/L2pzjaEm

Edition	Windows 11 Home
Version	22H2
Installed on	‎2/‎22/‎2023
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

on commit: 43cab3321f029e116877c1c6cf4f4df874498d1f

any ideas?

**Comment by bramtechs** [comment]
Hello,
the Windows version of this project tends to break quite a lot between commits as I primarily develop on Linux.

As of commit [aa03a93](https://github.com/bramtechs/basalt/commit/aa03a9331591c83a1c15526cf822ac93e7d75f9e) (main branch) it should compile and run on Windows again!

Keep in mind that this engine is in very early development and is not well optimized at the moment.
